### ISSUE TITLE
Cannot request device on Android 7.1.1

### ISSUE THREAD

**Issue by lcquoc** [EvanBacon/react-bluetooth#1]
@EvanBacon I tried to use 'navigator.bluetooth.requestDevice' on my current React project.
It works on Chrome for MacOS but it doesn't work on real Android tablet device.

**Comment by EvanBacon** [comment]
As expected, the API has very low coverage https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API#Browser_compatibility
